
-- ### POLYMARKET SUPABASE SCHEMA (JAVÍTOTT TÖRLÉSSEL) ###

-- 1. LÉPÉS: Függőségek és régi objektumok eltávolítása a HELYES sorrendben
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP FUNCTION IF EXISTS public.vote_market(bigint, text, text);
DROP TABLE IF EXISTS public.comments CASCADE;
DROP TABLE IF EXISTS public.markets CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 2. LÉPÉS: A 'markets' tábla létrehozása
CREATE TABLE public.markets (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid REFERENCES auth.users(id),
    question text NOT NULL,
    image text,
    description text,
    yes_votes integer NOT NULL DEFAULT 0,
    no_votes integer NOT NULL DEFAULT 0,
    contract_address text,
    option_a text DEFAULT 'YES'::text,
    option_b text DEFAULT 'NO'::text,
    market_type text NOT NULL DEFAULT 'STANDARD'::text,
    target_market_cap numeric,
    expires_at timestamp with time zone,
    status text NOT NULL DEFAULT 'OPEN'::text,
    CONSTRAINT markets_pkey PRIMARY KEY (id)
);

-- 3. LÉPÉS: A 'profiles' tábla létrehozása a felhasználóneveknek
CREATE TABLE public.profiles (
  id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  username TEXT UNIQUE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (id),
  CONSTRAINT username_length CHECK (char_length(username) >= 3 AND char_length(username) <= 15)
);

-- 4. LÉPÉS: A 'comments' tábla létrehozása (username nélkül)
CREATE TABLE public.comments (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    market_id bigint NOT NULL,
    user_id uuid NOT NULL REFERENCES auth.users(id),
    content text NOT NULL,
    CONSTRAINT comments_pkey PRIMARY KEY (id),
    CONSTRAINT comments_market_id_fkey FOREIGN KEY (market_id) REFERENCES public.markets(id) ON DELETE CASCADE
);

-- 5. LÉPÉS: RPC funkció létrehozása a szavazáshoz
CREATE OR REPLACE FUNCTION public.vote_market(p_market_id bigint, p_vote_type text, p_previous_vote text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF p_previous_vote IS NOT NULL THEN
    IF p_previous_vote = 'YES' THEN
      UPDATE public.markets SET yes_votes = yes_votes - 1 WHERE id = p_market_id;
    ELSIF p_previous_vote = 'NO' THEN
      UPDATE public.markets SET no_votes = no_votes - 1 WHERE id = p_market_id;
    END IF;
  END IF;

  IF p_vote_type = 'YES' THEN
    UPDATE public.markets SET yes_votes = yes_votes + 1 WHERE id = p_market_id;
  ELSIF p_vote_type = 'NO' THEN
    UPDATE public.markets SET no_votes = no_votes + 1 WHERE id = p_market_id;
  END IF;
END;
$function$;

-- 6. LÉPÉS: Funkció és trigger létrehozása új profilokhoz
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  username_val TEXT;
BEGIN
  IF new.email LIKE '%@phantom.app' THEN
    username_val := 'sol-' || substr(split_part(new.email, '@', 1), 1, 4) || '...' || substr(split_part(new.email, '@', 1), -4);
  ELSE
    username_val := split_part(new.email, '@', 1);
  END IF;
  INSERT INTO public.profiles (id, username)
  VALUES (new.id, username_val);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 7. LÉPÉS: Sor Szintű Biztonság (RLS) engedélyezése
ALTER TABLE public.markets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 8. LÉPÉS: RLS szabályok (policy-k) létrehozása
CREATE POLICY "Enable public read access for all users" ON public.markets FOR SELECT TO public USING (true);
CREATE POLICY "Allow insert for authenticated users" ON public.markets FOR INSERT TO public WITH CHECK (auth.role() = 'authenticated' AND auth.uid() = user_id);
CREATE POLICY "Enable public read access for all users" ON public.comments FOR SELECT TO public USING (true);
CREATE POLICY "Allow insert for authenticated users" ON public.comments FOR INSERT TO public WITH CHECK (auth.role() = 'authenticated' AND auth.uid() = user_id);
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);
