
-- ### POLYMARKET SUPABASE SCHEMA (VÉGLEGES JAVÍTÁS) ###
-- Ez a szkript először teljesen törli a régi, hibás táblákat, hogy tiszta alapot biztosítson.

-- 1. LÉPÉS: Régi, hibás táblák és funkciók eltávolítása (ha léteznek)
DROP TABLE IF EXISTS public.comments CASCADE;
DROP TABLE IF EXISTS public.markets CASCADE;
DROP FUNCTION IF EXISTS public.vote_market(bigint, text, text);

-- 2. LÉPÉS: A 'markets' tábla létrehozása a HELYES sémával
CREATE TABLE public.markets (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid REFERENCES auth.users(id),
    question text NOT NULL,
    image text,
    description text,
    yes_votes integer NOT NULL DEFAULT 0,
    no_votes integer NOT NULL DEFAULT 0,
    contract_address text,
    option_a text DEFAULT 'YES'::text,
    option_b text DEFAULT 'NO'::text,
    market_type text NOT NULL DEFAULT 'STANDARD'::text,
    target_market_cap numeric,
    expires_at timestamp with time zone,
    status text NOT NULL DEFAULT 'OPEN'::text,
    CONSTRAINT markets_pkey PRIMARY KEY (id)
);

-- 3. LÉPÉS: A 'comments' tábla létrehozása a HELYES sémával
CREATE TABLE public.comments (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    market_id bigint NOT NULL,
    user_id uuid NOT NULL REFERENCES auth.users(id),
    username text NOT NULL,
    content text NOT NULL,
    CONSTRAINT comments_pkey PRIMARY KEY (id),
    CONSTRAINT comments_market_id_fkey FOREIGN KEY (market_id) REFERENCES public.markets(id) ON DELETE CASCADE
);

-- 4. LÉPÉS: RPC funkció létrehozása a szavazáshoz
CREATE OR REPLACE FUNCTION public.vote_market(p_market_id bigint, p_vote_type text, p_previous_vote text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF p_previous_vote IS NOT NULL THEN
    IF p_previous_vote = 'YES' THEN
      UPDATE public.markets SET yes_votes = yes_votes - 1 WHERE id = p_market_id;
    ELSIF p_previous_vote = 'NO' THEN
      UPDATE public.markets SET no_votes = no_votes - 1 WHERE id = p_market_id;
    END IF;
  END IF;

  IF p_vote_type = 'YES' THEN
    UPDATE public.markets SET yes_votes = yes_votes + 1 WHERE id = p_market_id;
  ELSIF p_vote_type = 'NO' THEN
    UPDATE public.markets SET no_votes = no_votes + 1 WHERE id = p_market_id;
  END IF;
END;
$function$;

-- 5. LÉPÉS: Sor Szintű Biztonság (RLS) engedélyezése
ALTER TABLE public.markets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- 6. LÉPÉS: RLS szabályok (policy-k) létrehozása
-- A piacokat bárki olvashatja.
CREATE POLICY "Enable public read access for all users" ON public.markets
AS PERMISSIVE FOR SELECT TO public USING (true);

-- Piacokat csak bejelentkezett felhasználók hozhatnak létre, és a saját user_id-jukkal.
CREATE POLICY "Allow insert for authenticated users" ON public.markets
AS PERMISSIVE FOR INSERT TO public WITH CHECK (auth.role() = 'authenticated' AND auth.uid() = user_id);

-- A kommenteket bárki olvashatja.
CREATE POLICY "Enable public read access for all users" ON public.comments
AS PERMISSIVE FOR SELECT TO public USING (true);

-- Kommenteket csak bejelentkezett felhasználók hozhatnak létre, és csak a sajátjukat.
CREATE POLICY "Allow insert for authenticated users" ON public.comments
AS PERMISSIVE FOR INSERT TO public WITH CHECK (auth.role() = 'authenticated' AND auth.uid() = user_id);
