
import { PredictionMerket, MerketComment } from '../types';
import { supabase, isSupabaseConfigured } from './supabaseClient';

/**
 * SQL SCHEMA FOR SUPABASE (Run this in Supabase SQL Editor):
 * 
 * -- 1. Create Markets Table
 * CREATE TABLE markets (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   question TEXT NOT NULL,
 *   description TEXT,
 *   image TEXT,
 *   yes_votes BIGINT DEFAULT 0,
 *   no_votes BIGINT DEFAULT 0,
 *   contract_address TEXT,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 * 
 * -- 2. Create Comments Table
 * CREATE TABLE comments (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   market_id BIGINT REFERENCES markets(id) ON DELETE CASCADE,
 *   username TEXT NOT NULL,
 *   content TEXT NOT NULL,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 * 
 * -- 3. Create Voting Function (RPC)
 * CREATE OR REPLACE FUNCTION increment_vote(market_id bigint, vote_type text, previous_vote text default null)
 * RETURNS void AS $$
 * BEGIN
 *   -- Remove previous vote if exists
 *   IF previous_vote = 'YES' THEN
 *     UPDATE markets SET yes_votes = GREATEST(0, yes_votes - 1) WHERE id = market_id;
 *   ELSIF previous_vote = 'NO' THEN
 *     UPDATE markets SET no_votes = GREATEST(0, no_votes - 1) WHERE id = market_id;
 *   END IF;
 * 
 *   -- Add new vote
 *   IF vote_type = 'YES' THEN
 *     UPDATE markets SET yes_votes = yes_votes + 1 WHERE id = market_id;
 *   ELSIF vote_type = 'NO' THEN
 *     UPDATE markets SET no_votes = no_votes + 1 WHERE id = market_id;
 *   END IF;
 * END;
 * $$ LANGUAGE plpgsql;
 * 
 * -- 4. ENABLE RLS & CREATE POLICIES (Allow public read/write for this demo)
 * ALTER TABLE markets ENABLE ROW LEVEL SECURITY;
 * CREATE POLICY "Public Access" ON markets FOR ALL USING (true) WITH CHECK (true);
 * ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
 * CREATE POLICY "Public Access Comments" ON comments FOR ALL USING (true) WITH CHECK (true);
 */

const STORAGE_KEY = 'poly_market_data_v3';
const COMMENTS_KEY = 'poly_market_comments_v1';
const USER_VOTES_KEY = 'poly_user_votes_v3'; 
const BRAND_LOGO = "https://img.cryptorank.io/coins/polymarket1671006384460.png";

const FUNNY_INSIGHTS = [
  "Confidence scoring: High.",
  "Market sentiment: Extremely Bullish.",
  "Terminal activity: Peak volume.",
  "Industry report: $Polymarket dominance.",
  "Data source: On-chain truth.",
  "Accuracy: Verified by Oracle.",
  "Signal status: Strong Buy pressure."
];

const SEED_DATA: PredictionMerket[] = [
  {
    id: 'poly-1',
    question: 'Will $Polymarket reach 100M Market Cap by April?',
    yesVotes: 420,
    noVotes: 69,
    createdAt: Date.now(),
    image: BRAND_LOGO,
    description: "The ultimate survival metric. Monitoring growth velocity across the Solana ecosystem.",
    contractAddress: "9ftnbzpAP4SUkmHMoFuX4ofvDXCHxbrTXKiSFL4Wpump"
  }
];

export const fetchMarketCap = async (ca: string): Promise<string | null> => {
  if (!ca || ca.length < 32) return null;
  try {
    const response = await fetch(`https://api.dexscreener.com/latest/dex/tokens/${ca}`);
    const data = await response.json();
    if (data.pairs && data.pairs.length > 0) {
      const mcap = data.pairs[0].fdv || data.pairs[0].marketCap;
      if (mcap >= 1000000) return `${(mcap / 1000000).toFixed(2)}M`;
      if (mcap >= 1000) return `${(mcap / 1000).toFixed(1)}K`;
      return `${mcap}`;
    }
    return "N/A";
  } catch (err) {
    console.error("Dexscreener fetch error:", err);
    return null;
  }
};

export const getUserVote = (merketId: string): 'YES' | 'NO' | null => {
  try {
    const stored = localStorage.getItem(USER_VOTES_KEY);
    const votes = stored ? JSON.parse(stored) : {};
    return votes[merketId] || null;
  } catch (e) {
    return null;
  }
};

const saveUserVote = (merketId: string, option: 'YES' | 'NO') => {
  try {
    const stored = localStorage.getItem(USER_VOTES_KEY);
    const votes = stored ? JSON.parse(stored) : {};
    votes[merketId] = option;
    localStorage.setItem(USER_VOTES_KEY, JSON.stringify(votes));
  } catch (e) {
    console.error("Failed to save vote locally", e);
  }
};

export const getMerkets = async (): Promise<PredictionMerket[]> => {
  if (isSupabaseConfigured() && supabase) {
    try {
      const { data, error } = await supabase
        .from('markets')
        .select('id, question, yes_votes, no_votes, created_at, image, description, contract_address')
        .order('created_at', { ascending: false });
      
      if (error) {
        console.error("Supabase fetch error:", error.message);
      } else if (data) {
        return data.map((item: any) => ({
          id: item.id.toString(),
          question: item.question,
          yesVotes: parseInt(item.yes_votes || 0),
          noVotes: parseInt(item.no_votes || 0),
          createdAt: item.created_at ? new Date(item.created_at).getTime() : Date.now(),
          image: item.image,
          description: item.description || FUNNY_INSIGHTS[Math.floor(Math.random() * FUNNY_INSIGHTS.length)],
          contractAddress: item.contract_address
        }));
      }
    } catch (err) { 
      console.error("Supabase connection catch:", err); 
    }
  }

  // Fallback to local storage if Supabase fails or is not configured
  const stored = localStorage.getItem(STORAGE_KEY);
  let localData: PredictionMerket[] = stored ? JSON.parse(stored) : [];
  
  if (localData.length === 0) {
      localData = [...SEED_DATA];
      localStorage.setItem(STORAGE_KEY, JSON.stringify(localData));
  }
  
  return localData.sort((a, b) => b.createdAt - a.createdAt);
};

export const createMarket = async (market: Omit<PredictionMerket, 'id' | 'yesVotes' | 'noVotes' | 'createdAt'>): Promise<void> => {
    if (isSupabaseConfigured() && supabase) {
        try {
          const { error } = await supabase.from('markets').insert([{
              question: market.question,
              description: market.description,
              image: market.image,
              yes_votes: 0,
              no_votes: 0,
              contract_address: market.contractAddress
          }]);
          
          if (!error) {
            console.log("Market created in Supabase successfully.");
            return;
          }
          
          console.error("Supabase insert error:", error.message);
          // If error is RLS or table missing, it falls through to localstorage
        } catch (err) {
          console.error("Supabase insert catch:", err);
        }
    }

    // Local Storage Fallback
    const newMarket: PredictionMerket = {
        ...market,
        id: `local-${crypto.randomUUID()}`,
        yesVotes: 0,
        noVotes: 0,
        createdAt: Date.now(),
        image: market.image || BRAND_LOGO
    };

    const stored = localStorage.getItem(STORAGE_KEY);
    const currentMarkets: PredictionMerket[] = stored ? JSON.parse(stored) : [];
    localStorage.setItem(STORAGE_KEY, JSON.stringify([newMarket, ...currentMarkets]));
};

export const voteMerket = async (id: string, option: 'YES' | 'NO'): Promise<void> => {
  const previousVote = getUserVote(id);
  if (previousVote === option) return;

  if (isSupabaseConfigured() && supabase && !id.startsWith('local-')) {
    try {
      const { error } = await supabase.rpc('increment_vote', { 
          market_id: parseInt(id), 
          vote_type: option,
          previous_vote: previousVote 
      });
      
      if (!error) {
        saveUserVote(id, option);
        return;
      }
      console.error("RPC error:", error.message);
    } catch (err) {
      console.error("RPC catch:", err);
    }
  }
  
  // Local fallback
  const stored = localStorage.getItem(STORAGE_KEY);
  const merkets: PredictionMerket[] = stored ? JSON.parse(stored) : [];
  const updated = merkets.map((m: PredictionMerket) => {
    if (m.id !== id) return m;
    
    let newYes = m.yesVotes;
    let newNo = m.noVotes;

    if (previousVote === 'YES') newYes = Math.max(0, newYes - 1);
    if (previousVote === 'NO') newNo = Math.max(0, newNo - 1);

    if (option === 'YES') newYes += 1;
    if (option === 'NO') newNo += 1;

    return { ...m, yesVotes: newYes, noVotes: newNo };
  });
  
  localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
  saveUserVote(id, option);
};

export const getComments = async (marketId: string): Promise<MerketComment[]> => {
  if (isSupabaseConfigured() && supabase && !marketId.startsWith('local-')) {
    try {
      const { data, error } = await supabase
        .from('comments')
        .select('*')
        .eq('market_id', parseInt(marketId))
        .order('created_at', { ascending: false });
      if (!error && data) return data;
      if (error) console.error("Comments fetch error:", error.message);
    } catch (err) {
      console.error("Comments fetch catch:", err);
    }
  }
  const stored = localStorage.getItem(COMMENTS_KEY);
  const allComments: MerketComment[] = stored ? JSON.parse(stored) : [];
  return allComments.filter(c => c.market_id === marketId).sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
};

export const postComment = async (marketId: string, username: string, content: string): Promise<void> => {
  if (!username.trim() || !content.trim()) return;
  if (isSupabaseConfigured() && supabase && !marketId.startsWith('local-')) {
    try {
      const { error } = await supabase.from('comments').insert([{ 
        market_id: parseInt(marketId), 
        username, 
        content 
      }]);
      if (!error) return;
      console.error("Comment post error:", error.message);
    } catch (err) {
      console.error("Comment post catch:", err);
    }
  }
  const stored = localStorage.getItem(COMMENTS_KEY);
  const allComments = stored ? JSON.parse(stored) : [];
  const newComment = { id: crypto.randomUUID(), market_id: marketId, username, content, created_at: new Date().toISOString() };
  localStorage.setItem(COMMENTS_KEY, JSON.stringify([newComment, ...allComments]));
};
